# Generated by Django 2.2.2 on 2019-06-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='IssuingNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=19)),
                ('cvv', models.CharField(max_length=3)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=4)),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycreditcards.CardHolder')),
                ('issuing_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycreditcards.IssuingNetwork')),
            ],
        ),
    ]
